core = "7.x"
api = "2"

projects[views_megarow][subdir] = "contrib"
projects[commerce][subdir] = "contrib"
projects[commerce_backoffice][subdir] = "contrib"
projects[commerce_features][subdir] = "contrib"
projects[commerce_entitycache][subdir] = "contrib"
projects[commerce_autosku][subdir] = "contrib"
projects[inline_entity_form][subdir] = "contrib"
